src/Entity/Plats.php
<?php

namespace App\Entity;

use App\Repository\PlatsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PlatsRepository::class)]
class Plats
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Name = null;

    #[ORM\Column(length: 255)]
    private ?string $Description = null;

    #[ORM\Column(length: 255)]
    private ?string $Price = null;

    #[ORM\Column(length: 255)]
    private ?string $Type = null;

    #[ORM\ManyToMany(targetEntity: Menus::class, mappedBy: 'entrees')]
    private Collection $menuses;

    public function __toString()
    {
        return $this->getName();
    }

    public function __construct()
    {
        $this->menuses = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getPrice(): ?string
    {
        return $this->Price;
    }

    public function setPrice(string $Price): self
    {
        $this->Price = $Price;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->Type;
    }

    public function setType(string $Type): self
    {
        $this->Type = $Type;

        return $this;
    }

    /**
     * @return Collection<int, Menus>
     */
    public function getMenuses(): Collection
    {
        return $this->menuses;
    }

    public function addMenus(Menus $menus): self
    {
        if (!$this->menuses->contains($menus)) {
            $this->menuses->add($menus);
            $menus->addEntree($this);
        }

        return $this;
    }

    public function removeMenus(Menus $menus): self
    {
        if ($this->menuses->removeElement($menus)) {
            $menus->removeEntree($this);
        }

        return $this;
    }
}

src/Controller/CarteController.php
<?php

namespace App\Controller;

use App\Entity\Parameters;
use App\Repository\MenusRepository;
use App\Repository\PlatsRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class CarteController extends AbstractController
{
    public function __construct(EntityManagerInterface $entityManager){
        $this->entityManager = $entityManager;
    }
    #[Route('/carte', name: 'app_carte')]
    public function index(PlatsRepository $platsRepository, MenusRepository $menusRepository): Response
    {
        $param = $this->entityManager->getRepository(Parameters::class)->findById('1');
        return $this->render('carte/index.html.twig', [
            'controller_name' => 'CarteController',
            'entrees' => $platsRepository->findBy(['Type' => 'Entrée']),
            'plats' => $platsRepository->findBy(['Type' => 'Plat principal']),
            'desserts' => $platsRepository->findBy(['Type' => 'dessert']),
            'Vins' => $platsRepository->findBy(['Type' => 'Vin']),
            'Sodas' => $platsRepository->findBy(['Type' => 'Soda']),
            'Eaux' => $platsRepository->findBy(['Type' => 'Eau']),
            'menus' => $menusRepository->findAll(),
            'param' => $param,

        ]);
    }
}

templates/carte/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello CarteController!{% endblock %}

{% block body %}

    <div class="container">

        <div class="d-flex align-items-center justify-content-center mt-4">
            <img class="logomenu img-fluid" src="{{ asset('asset/image/imgdoss.png') }}">
            <h2 class="mt-3">Nos cartes et menus</h2>
            <img class="logomenu img-fluid" src="{{ asset('asset/image/imgdoss.png') }}">
        </div>

        <div class="container col-md-10 d-flex align-items-center justify-content-center">
            <div class="card borderGreen mt-5 p-3">
                <div class="d-flex align-items-center justify-content-center">
                    <img class="logomenu img-fluid" src="{{ asset('asset/image/imgdoss.png') }}">
                    <h2 class="mt-3">Notre carte</h2>
                    <img class="logomenu img-fluid" src="{{ asset('asset/image/imgdoss.png') }}">
                </div>

                <ul class="mt-1">
                    <p class="textMenu text-center text-primary">Entrées</p>
                    {% for plat in entrees %}
                    <li class="text-dark text-center"><b>{{ plat.name }}</b><span class="ms-1">{{ plat.price }} €</span></br><small>{{ plat.description }}</small></li></br>
                    {% endfor %}
                </ul>

                <ul>
                    <p class="textMenu text-center text-primary">Plats</p>
                    {% for plat in plats %}
                        <li class="text-dark text-center"><b>{{ plat.name }}</b><span class="ms-1">{{ plat.price }} €</span></br><small>{{ plat.description }}</small></li></br>
                    {% endfor %}
                </ul>

                <ul>
                    <p class="textMenu text-center text-primary">Desserts</p>
                    {% for plat in desserts %}
                        <li class="text-dark text-center"><b>{{ plat.name }}</b><span class="ms-1">{{ plat.price }} €</span></br><small>{{ plat.description }}</small></li></br>
                    {% endfor %}
                </ul>
            </div>
        </div>

        <div class="container col-md-10 d-flex align-items-center justify-content-center">
            <div class="card borderGreen mt-5">
                <div class="d-flex align-items-center justify-content-center">
                    <img class="logomenu img-fluid" src="{{ asset('asset/image/imgdoss.png') }}">
                    <h2 class="mt-3">Carte des Vins et boissons</h2>
                    <img class="logomenu img-fluid" src="{{ asset('asset/image/imgdoss.png') }}">
                </div>

                <ul class="mt-1">
                    <p class="textMenu text-center text-primary">Vins</p>
                    {% for plat in Vins %}
                        <li class="px-5 text-dark text-center"><b>{{ plat.name }}</b><span class="ms-1">{{ plat.price }} €</span></br><span class="small">{{ plat.description }}</span></li></br>
                    {% endfor %}
                </ul>
                <div class="row">
                    <div class="col-md-6">
                        <ul>
                            <p class="textMenu text-center text-primary">Eaux</p>
                            {% for plat in Eaux %}
                                <li class="text-dark text-center"><b>{{ plat.name }}</b><span class="ms-1">{{ plat.price }} €</span></br><small>{{ plat.description }}</small></li></br>
                            {% endfor %}
                        </ul>
                    </div>

                    <div class="col-md-6">
                        <ul>
                            <p class="textMenu text-center text-primary">Sodas</p>
                            {% for plat in Sodas %}
                                <li class="text-dark text-center"><b>{{ plat.name }}</b><span class="ms-1">{{ plat.price }} €</span></br><small>{{ plat.description }}</small></li></br>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>



        <div class="container col-md-6 d-flex flex-column align-items-start justify-content-center">
        {% for menu in menus %}
            <div class="card fondvert w-100 mt-5">
                <div class="d-flex align-items-center justify-content-center">
                    <img class="logomenu img-fluid" src="{{ asset('asset/image/imgdoss.png') }}">
                    <h2 class="mt-3">{{ menu.name }}</h2>
                    <img class="logomenu img-fluid" src="{{ asset('asset/image/imgdoss.png') }}">
                </div>

                {% if menu.entrees|length > 0 %}
                <ul class="mt-1"><br>
                    <p class="textMenu">Entrés :</p>
                    {% for plat in menu.entrees %}
                    <li class="mt-2">{{ plat.name }}</li>
                    {% endfor %}
                </ul>
                {% endif %}

                <ul class="mt-1"><br>
                    <p class="textMenu">Plats :</p>
                    {% for plat in menu.principale %}
                        <li class="mt-2">{{ plat.name }}</li>
                    {% endfor %}
                </ul>

                <ul class="mt-1"><br>
                    <p class="textMenu">Desserts :</p>
                    {% for plat in menu.desserts %}
                        <li class="mt-2">{{ plat.name }}</li>
                    {% endfor %}
                </ul>


                <p class="text-center">{{ menu.price }} euros, {% if menu.entrees|length > 0 %} entrée, {% endif %} plat, dessert.</p>
            </div>
        {% endfor %}
        </div>
    </div>


{% endblock %}